---
  - name: Install Yum packages
    yum: name={{ item }} state=present update_cache=yes
    with_items:
      - nodejs
      - npm
      - git
      - bind-utils
      - wget

  - name: Update MailHops API
    git: repo={{ git_repo }} dest={{ root_web_dir }} force=yes

  - name: Copy MailHops config
    template: src=config.json dest="{{ root_web_dir }}/config.json"

  - name: Get composer
    get_url: url="https://getcomposer.org/download/{{ composer_version }}/composer.phar" dest=/usr/local/bin/composer mode=755

  - name: Run composer on v1
    command: "/usr/local/bin/composer {{ item }}"
    args:
      chdir: "{{ root_web_dir }}/v1"
    with_items:
      - update
      - install

  - name: Run composer on v2
    command: "/usr/local/bin/composer {{ item }}"
    args:
      chdir: "{{ root_web_dir }}/v2"
    with_items:
      - update
      - install

  - name: Update NPM directories
    file: path="{{ root_web_dir }}/{{ item }}" state=directory group=nginx owner=nginx
    with_items:
      - bower_components
      - node_modules

  - name: Run NPM
    command: "{{ item }}"
    args:
      chdir: "{{ root_web_dir }}"
    with_items:
      - npm install
      # - bower install

  - name: Create directory
    file: path="{{ root_web_dir }}/geoip" state=directory owner=nginx group=nginx

  - name: Install GeoIP Cron
    cron: name="geoip update" weekday=3 job="{{ root_web_dir }}/cron_get_geoip.sh > /dev/null"
    when: cron_on

  - name: Update GeoIP perms
    file: path="{{ root_web_dir }}/cron_get_geoip.sh" mode=755

  - name: Update GeoIP
    shell: "{{ root_web_dir }}/cron_get_geoip.sh"

  - name: Install Metrics Cron
    cron: name="cachet metrics" minute=*/5 job="php {{ root_web_dir }}/v2/scripts/metrics.php > /dev/null"
    when: cron_on and groups['api'][0] == inventory_hostname

  - name: Post Commands
    command: "{{ item }}"
    with_items:
      - setsebool -P httpd_can_network_connect 1

  - name: Set NGINX perms on directory
    file: path="{{ root_web_dir }}" state=directory owner=nginx group=nginx recurse=yes
